net use \\raktar.local\Copper       /USER:francois theglacer
net use \\raktar.local\Copper_Audio /USER:francois theglacer
net use \\raktar.local\Elements     /USER:francois theglacer
net use \\raktar.local\Emerald      /USER:francois theglacer
net use \\raktar.local\Mauve        /USER:francois theglacer
net use \\raktar.local\Mauve_Audio  /USER:francois theglacer
net use \\raktar.local\MyBook       /USER:francois theglacer
net use \\raktar.local\Slim         /USER:francois theglacer
net use \\raktar.local\Storage      /USER:francois theglacer
net use \\raktar.local\Tangerine    /USER:francois theglacer
net use \\raktar.local\Videos       /USER:francois theglacer
net use \\raktar.local\OMV          /USER:francois theglacer
